# Generated by Django 4.2.3 on 2023-07-26 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlacesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place_name", models.CharField(default="")),
                ("description", models.TextField(default="")),
                ("latitude", models.CharField(default="")),
                ("longitude", models.CharField(default="")),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "user_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Userplace",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
